[workspace]
members = [
    ".",
    "safe_math_macros",
    "tests/generated",
    "examples/basic",
    "examples/derive"
]

[package]
name = "safe_math"
version = "0.1.0"
edition = "2021"

[features]
derive = ["safe_math_macros/derive"]

[dependencies]
safe_math_macros = { path = "./safe_math_macros" }

[dev-dependencies]
proptest = "1.7.0"
proptest-derive = "0.6.0"
rand = "0.9.1"
rayon = "1.10.0"
simple-tqdm = { version = "0.2.0", features = ["rayon"] }

[build-dependencies]
rand = "0.9.1"
