[package]
name = "safe_math_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "fold"] }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "3"
