[package]
name = "safe_math_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
derive = ["num-traits"]

[dependencies]
syn = { version = "2", features = ["full", "fold"] }
quote = "1"
proc-macro2 = "1"
num-traits = { version = "0.2.19", optional = true }
